# Airflow - Dag (required, to airflow to recognize this as a dag).

"""
# Download STG measures

This DAG downloads measures from the client's FTP server.

- Client: 0142
- Model: STG

"""

import pendulum

from ingest.stg.measures.base_dag import MeasureSTGDag

MeasureSTGDag(
    "0142-stg-measures-ingest",
    **{
        "schedule_interval": "0 * * * *",
        "max_active_runs": 1,
        "tags": ["0142", "stg", "measures"],
        "catchup": False,
        "dagrun_timeout": pendulum.duration(minutes=50),
        "default_args": {
            "owner": "Airflow",
            "start_date": pendulum.datetime(2024, 8, 12, tz="UTC"),
            "retries": 1,
            "retry_delay": pendulum.duration(minutes=5),
        },
        "doc_md": __doc__,
        "task_params": {
            "measures_task": {
                "ssh_conn_id": "dielenor-vm",
                "protocol": "ftp",
                "file_paths": " ".join(
                    [
                        "/ex_sincroct/ct_alcobendas/upload",
                        "/ex_sincroct/ct_almagreras/upload",
                        "/ex_sincroct/ct_andalucia/upload",
                        "/ex_sincroct/ct_auxmontoro/upload",
                        "/ex_sincroct/ct_ave01/upload",
                        "/ex_sincroct/ct_ave02/upload",
                        "/ex_sincroct/ct_ave03/upload",
                        "/ex_sincroct/ct_ave05/upload",
                        "/ex_sincroct/ct_ave06/upload",
                        "/ex_sincroct/ct_ave07/upload",
                        "/ex_sincroct/ct_ave08/upload",
                        "/ex_sincroct/ct_biblioteca/upload",
                        "/ex_sincroct/ct_bretes230/upload",
                        "/ex_sincroct/ct_calvario230/upload",
                        "/ex_sincroct/ct_calvario400/upload",
                        "/ex_sincroct/ct_canuelo230/upload",
                        "/ex_sincroct/ct_canuelo400/upload",
                        "/ex_sincroct/ct_cdeportes230/upload",
                        "/ex_sincroct/ct_cdeportes400/upload",
                        "/ex_sincroct/ct_clh/upload",
                        "/ex_sincroct/ct_coca/upload",
                        "/ex_sincroct/ct_cortijoalmagreras/upload",
                        "/ex_sincroct/ct_ctraobejo/upload",
                        "/ex_sincroct/ct_depuradora/upload",
                        "/ex_sincroct/ct_emisora/upload",
                        "/ex_sincroct/ct_fabrica/upload",
                        "/ex_sincroct/ct_fabrica400/upload",
                        "/ex_sincroct/ct_hospital/upload",
                        "/ex_sincroct/ct_jagutierrez/upload",
                        "/ex_sincroct/ct_jara400/upload",
                        "/ex_sincroct/ct_juandelopez400/upload",
                        "/ex_sincroct/ct_juanhiguera/upload",
                        "/ex_sincroct/ct_julioromero/upload",
                        "/ex_sincroct/ct_ladehesilla/upload",
                        "/ex_sincroct/ct_lashazas/upload",
                        "/ex_sincroct/ct_lepanto230/upload",
                        "/ex_sincroct/ct_lepanto400/upload",
                        "/ex_sincroct/ct_luna/upload",
                        "/ex_sincroct/ct_magdalena/upload",
                        "/ex_sincroct/ct_martires/upload",
                        "/ex_sincroct/ct_mateotorres/upload",
                        "/ex_sincroct/ct_mauxiliadora/upload",
                        "/ex_sincroct/ct_navaluenga01/upload",
                        "/ex_sincroct/ct_navaluenga03/upload",
                        "/ex_sincroct/ct_navaluenga04/upload",
                        "/ex_sincroct/ct_navaluenga05/upload",
                        "/ex_sincroct/ct_navaluenga06/upload",
                        "/ex_sincroct/ct_navaluenga07/upload",
                        "/ex_sincroct/ct_norte/upload",
                        "/ex_sincroct/ct_nuevozarza/upload",
                        "/ex_sincroct/ct_obejuelo01/upload",
                        "/ex_sincroct/ct_obejuelo02/upload",
                        "/ex_sincroct/ct_obejuelo03/upload",
                        "/ex_sincroct/ct_obejuelo04/upload",
                        "/ex_sincroct/ct_obejuelo05/upload",
                        "/ex_sincroct/ct_obejuelo06/upload",
                        "/ex_sincroct/ct_obejuelo07/upload",
                        "/ex_sincroct/ct_obejuelo08/upload",
                        "/ex_sincroct/ct_obejuelo09/upload",
                        "/ex_sincroct/ct_obejuelo10/upload",
                        "/ex_sincroct/ct_obejuelo11/upload",
                        "/ex_sincroct/ct_obejuelo12/upload",
                        "/ex_sincroct/ct_olivo/upload",
                        "/ex_sincroct/ct_olivob/upload",
                        "/ex_sincroct/ct_oriente230/upload",
                        "/ex_sincroct/ct_oriente400/upload",
                        "/ex_sincroct/ct_pabloiglesias/upload",
                        "/ex_sincroct/ct_pcarnico/upload",
                        "/ex_sincroct/ct_petro2/upload",
                        "/ex_sincroct/ct_pilar/upload",
                        "/ex_sincroct/ct_pindustrial01/upload",
                        "/ex_sincroct/ct_pindustrial02/upload",
                        "/ex_sincroct/ct_pindustrial03/upload",
                        "/ex_sincroct/ct_pindustrial04/upload",
                        "/ex_sincroct/ct_pioxii/upload",
                        "/ex_sincroct/ct_pizarra00/upload",
                        "/ex_sincroct/ct_pizarra01/upload",
                        "/ex_sincroct/ct_pizarra02/upload",
                        "/ex_sincroct/ct_pizarra04/upload",
                        "/ex_sincroct/ct_pizarra05/upload",
                        "/ex_sincroct/ct_pizarra06/upload",
                        "/ex_sincroct/ct_pizarra07/upload",
                        "/ex_sincroct/ct_pizarra08/upload",
                        "/ex_sincroct/ct_pizarra09/upload",
                        "/ex_sincroct/ct_plazapaz/upload",
                        "/ex_sincroct/ct_promi/upload",
                        "/ex_sincroct/ct_quintillo/upload",
                        "/ex_sincroct/ct_real400/upload",
                        "/ex_sincroct/ct_rozuela01/upload",
                        "/ex_sincroct/ct_rozuela02/upload",
                        "/ex_sincroct/ct_rozuela03/upload",
                        "/ex_sincroct/ct_rozuela04/upload",
                        "/ex_sincroct/ct_rozuela05/upload",
                        "/ex_sincroct/ct_rozuela06/upload",
                        "/ex_sincroct/ct_saliega00/upload",
                        "/ex_sincroct/ct_saliega02/upload",
                        "/ex_sincroct/ct_saliega03/upload",
                        "/ex_sincroct/ct_saliega04/upload",
                        "/ex_sincroct/ct_saliega05/upload",
                        "/ex_sincroct/ct_saliega07/upload",
                        "/ex_sincroct/ct_saliega08/upload",
                        "/ex_sincroct/ct_sol/upload",
                        "/ex_sincroct/ct_sur/upload",
                        "/ex_sincroct/ct_tomasrey/upload",
                        "/ex_sincroct/ct_tren1/upload",
                        "/ex_sincroct/ct_tren2/upload",
                        "/ex_sincroct/ct_vinas01/upload",
                        "/ex_sincroct/ct_vinas02/upload",
                        "/ex_sincroct/ct_vinas03/upload",
                        "/ex_sincroct/ct_zarza230/upload",
                        "/ex_sincroct/ct_zarza400/upload",
                    ]
                ),
            }
        },
    },
)
